#include <libcurl/headers.hxx>
#include <stdexcept>

namespace libcurl {
auto getHeaderName(headers header) -> std::string {
    switch (header) {
        case headers::WWW_AUTHENTICATE:
            return "WWW-Authenticate";
        case headers::AUTHORIZATION:
            return "Authorization";
        case headers::PROXY_AUTHENTICATE:
            return "Proxy-Authenticate";
        case headers::PROXY_AUTHORIZATION:
            return "Proxy-Authorization";
        case headers::AGE:
            return "Age";
        case headers::CACHE_CONTROL:
            return "Cache-Control";
        case headers::CLEAR_SITE_DATA:
            return "Clear-Site-Data";
        case headers::EXPIRES:
            return "Expires";
        case headers::LAST_MODIFIED:
            return "Last-Modified";
        case headers::ETAG:
            return "ETag";
        case headers::IF_MATCH:
            return "If-Match";
        case headers::IF_NONE_MATCH:
            return "If-None-Match";
        case headers::IF_MODIFIED_SINCE:
            return "If-Modified-Since";
        case headers::IF_UNMODIFIED_SINCE:
            return "If-Unmodified-Since";
        case headers::VARY:
            return "Vary";
        case headers::CONNECTION:
            return "Connection";
        case headers::KEEP_ALIVE:
            return "Keep-Alive";
        case headers::ACCEPT:
            return "Accept";
        case headers::ACCEPT_ENCODING:
            return "Accept-Encoding";
        case headers::ACCEPT_LANGUAGE:
            return "Accept-Language";
        case headers::ACCEPT_PATCH:
            return "Accept-Patch";
        case headers::ACCEPT_POST:
            return "Accept-Post";
        case headers::EXPECT:
            return "Expect";
        case headers::MAX_FORWARDS:
            return "Max-Forwards";
        case headers::COOKIE:
            return "Cookie";
        case headers::SET_COOKIE:
            return "Set-Cookie";
        case headers::ACCESS_CONTROL_ALLOW_CREDENTIALS:
            return "Access-Control-Allow-Credentials";
        case headers::ACCESS_CONTROL_ALLOW_HEADERS:
            return "Access-Control-Allow-Headers";
        case headers::ACCESS_CONTROL_ALLOW_METHODS:
            return "Access-Control-Allow-Methods";
        case headers::ACCESS_CONTROL_ALLOW_ORIGIN:
            return "Access-Control-Allow-Origin";
        case headers::ACCESS_CONTROL_EXPOSE_HEADERS:
            return "Access-Control-Expose-Headers";
        case headers::ACCESS_CONTROL_MAX_AGE:
            return "Access-Control-Max-Age";
        case headers::ACCESS_CONTROL_REQUEST_HEADERS:
            return "Access-Control-Request-Headers";
        case headers::ACCESS_CONTROL_REQUEST_METHOD:
            return "Access-Control-Request-Method";
        case headers::ORIGIN:
            return "Origin";
        case headers::TIMING_ALLOW_ORIGIN:
            return "Timing-Allow-Origin";
        case headers::CONTENT_DISPOSITION:
            return "Content-Disposition";
        case headers::INTEGRITY_POLICY:
            return "Integrity-Policy";
        case headers::INTEGRITY_POLICY_REPORT_ONLY:
            return "Integrity-Policy-Report-Only";
        case headers::CONTENT_LENGTH:
            return "Content-Length";
        case headers::CONTENT_TYPE:
            return "Content-Type";
        case headers::CONTENT_ENCODING:
            return "Content-Encoding";
        case headers::CONTENT_LANGUAGE:
            return "Content-Language";
        case headers::CONTENT_LOCATION:
            return "Content-Location";
        case headers::PREFER:
            return "Prefer";
        case headers::PREFERENCE_APPLIED:
            return "Preference-Applied";
        case headers::FORWARDED:
            return "Forwarded";
        case headers::VIA:
            return "Via";
        case headers::ACCEPT_RANGES:
            return "Accept-Ranges";
        case headers::RANGE:
            return "Range";
        case headers::IF_RANGE:
            return "If-Range";
        case headers::CONTENT_RANGE:
            return "Content-Range";
        case headers::LOCATION:
            return "Location";
        case headers::REFRESH:
            return "Refresh";
        case headers::FROM:
            return "From";
        case headers::HOST:
            return "Host";
        case headers::REFERER:
            return "Referer";
        case headers::REFERRER_POLICY:
            return "Referrer-Policy";
        case headers::USER_AGENT:
            return "User-Agent";
        case headers::ALLOW:
            return "Allow";
        case headers::SERVER:
            return "Server";
        case headers::CROSS_ORIGIN_EMBEDDER_POLICY:
            return "Cross-Origin-Embedder-Policy";
        case headers::CROSS_ORIGIN_OPENER_POLICY:
            return "Cross-Origin-Opener-Policy";
        case headers::CROSS_ORIGIN_RESOURCE_POLICY:
            return "Cross-Origin-Resource-Policy";
        case headers::CONTENT_SECURITY_POLICY:
            return "Content-Security-Policy";
        case headers::CONTENT_SECURITY_POLICY_REPORT_ONLY:
            return "Content-Security-Policy-Report-Only";
        case headers::PERMISSIONS_POLICY:
            return "Permissions-Policy";
        case headers::STRICT_TRANSPORT_SECURITY:
            return "Strict-Transport-Security";
        case headers::UPGRADE_INSECURE_REQUESTS:
            return "Upgrade-Insecure-Requests";
        case headers::X_CONTENT_TYPE_OPTIONS:
            return "X-Content-Type-Options";
        case headers::X_FRAME_OPTIONS:
            return "X-Frame-Options";
        case headers::X_PERMITTED_CROSS_DOMAIN_POLICIES:
            return "X-Permitted-Cross-Domain-Policies";
        case headers::X_POWERED_BY:
            return "X-Powered-By";
        case headers::X_XSS_PROTECTION:
            return "X-XSS-Protection";
        case headers::SEC_FETCH_SITE:
            return "Sec-Fetch-Site";
        case headers::SEC_FETCH_MODE:
            return "Sec-Fetch-Mode";
        case headers::SEC_FETCH_USER:
            return "Sec-Fetch-User";
        case headers::SEC_FETCH_DEST:
            return "Sec-Fetch-Dest";
        case headers::SEC_PURPOSE:
            return "Sec-Purpose";
        case headers::SERVICE_WORKER_NAVIGATION_PRELOAD:
            return "Service-Worker-Navigation-Preload";
        case headers::SEC_FETCH_STORAGE_ACCESS:
            return "Sec-Fetch-Storage-Access";
        case headers::ACTIVATE_STORAGE_ACCESS:
            return "Activate-Storage-Access";
        case headers::REPORTING_ENDPOINTS:
            return "Reporting-Endpoints";
        case headers::TRANSFER_ENCODING:
            return "Transfer-Encoding";
        case headers::TE:
            return "TE";
        case headers::TRAILER:
            return "Trailer";
        case headers::SEC_WEBSOCKET_ACCEPT:
            return "Sec-WebSocket-Accept";
        case headers::SEC_WEBSOCKET_EXTENSIONS:
            return "Sec-WebSocket-Extensions";
        case headers::SEC_WEBSOCKET_KEY:
            return "Sec-WebSocket-Key";
        case headers::SEC_WEBSOCKET_PROTOCOL:
            return "Sec-WebSocket-Protocol";
        case headers::SEC_WEBSOCKET_VERSION:
            return "Sec-WebSocket-Version";
        case headers::ALT_SVC:
            return "Alt-Svc";
        case headers::ALT_USED:
            return "Alt-Used";
        case headers::DATE:
            return "Date";
        case headers::LINK:
            return "Link";
        case headers::RETRY_AFTER:
            return "Retry-After";
        case headers::SERVER_TIMING:
            return "Server-Timing";
        case headers::SERVICE_WORKER:
            return "Service-Worker";
        case headers::SERVICE_WORKER_ALLOWED:
            return "Service-Worker-Allowed";
        case headers::SOURCEMAP:
            return "SourceMap";
        case headers::UPGRADE:
            return "Upgrade";
        case headers::PRIORITY:
            return "Priority";
        case headers::ATTRIBUTION_REPORTING_ELIGIBLE:
            return "Attribution-Reporting-Eligible";
        case headers::ATTRIBUTION_REPORTING_REGISTER_SOURCE:
            return "Attribution-Reporting-Register-Source";
        case headers::ATTRIBUTION_REPORTING_REGISTER_TRIGGER:
            return "Attribution-Reporting-Register-Trigger";
        case headers::ACCEPT_CH:
            return "Accept-CH";
        default: // unreachable
            throw std::logic_error("Header not implemented");
    }
}
} // namespace libcurl
